### ISSUE TITLE
Ip spoofing range

### ISSUE THREAD

**Issue by Takumi86ES** [dennorske/samp-packet-proxy#7]
Any solution for spoofing ip ranges? They attack me at ranges 180. 190. which makes users disconnect and I am alone on the server with people from Spain. Those ranges are latin ips. Argentina, Venezuela ...

**Comment by Takumi86ES** [comment]
Sorry for the misuse.

**Comment by dennorske** [comment]
Hi!

Unfortunately UDP packet spoofing is incredibly hard to work around, and this is mainly due to there not being any "handshakes" between the client and the server. These ip's are very likely to be all fake, and if you try to block them, you may end up blocking legit traffic as well. 

So you can either do the following:
1. Shut down your server and hope it stops soon. Answering all the traffic may get you prone to a reflection attack (you answering all these ip's can make it look like you're attacking someone back) 
2. Use my script to increase the rate at which the server responds at. This makes the server at least show online since everything is answered.

**Comment by Takumi86ES** [comment]
The problem is that although the query answers, people cannot enter. It has no ping. The server goes out for them.

**Comment by dennorske** [comment]
It sounds like you are facing a slightly different attack than what this script is intended to handle then.. 
Can you give me your server specs / os you are running at? 

Also can you run ngrep for me to get the traffic on the interface on port 7777?
`sudo ngrep -x -d eth0 udp port 7777 > dump.txt`
Run it for only 5 seconds (max!) Press `ctrl+c` to stop it
replace eth0 with your network interface, and 7777 with your port.
Send me the dump.txt when done.

**Comment by Takumi86ES** [comment]
OVH Game. Dedicated.

I have created the file but there is nothing inside.

**Comment by dennorske** [comment]
I see, my theory is that this is not an attack to make you appear offline by spamming the query mechanism, but rather an attack to make your server unable to accept connections.

Can you run a similar command again, to get traffic from all ports? 

`sudo ngrep -x -d eth0 udp > UDP_dump.txt`

This time it might be a massive amount of packets (talking megabytes of prints per sec) so only run it for **maximum 3-5 seconds** :)

**Comment by Takumi86ES** [comment]
Again the same. "1066 received" appears but the connections do not appear as such.

**Comment by dennorske** [comment]
Can I have a chance to chat with you on Discord if you have that? 
denNorske#6741 is my id

I'd like to help you out as best as possible, however, I don't see this as a fit platform :)
